### ISSUE TITLE
exception occured after running "emu-docker interactive --start"

### ISSUE THREAD

**Issue by clgwlg** [google/android-emulator-container-scripts#121]
Traceback (most recent call last):
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urlfetch-1.1.3-py3.7.egg/urlfetch.py", line 740, in request
    conn.request(method, request_url, data, reqheaders)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/android-emulator-container-scripts-master/venv/bin/emu-docker", line 11, in <module>
    load_entry_point('emu-docker', 'console_scripts', 'emu-docker')()
  File "/Users/liangchen/Downloads/android-emulator-container-scripts-master/emu/emu_docker.py", line 269, in main
    args.func(args)
  File "/android-emulator-container-scripts-master/emu/emu_docker.py", line 111, in create_docker_image_interactive
    img = emu_downloads_menu.select_image(args.arm) or sys.exit(1)
  File "/android-emulator-container-scripts-master/emu/emu_downloads_menu.py", line 388, in select_image
    img_infos = get_images_info(arm)
  File "/android-emulator-container-scripts-master/emu/emu_downloads_menu.py", line 320, in get_images_info
    response = urlfetch.get(url)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urlfetch-1.1.3-py3.7.egg/urlfetch.py", line 745, in request
    raise UrlfetchException(e)
urlfetch.UrlfetchException: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

**Comment by pokowaka** [comment]
This has most likely something to do with your python installation. The system is unable to validate the certificates associated with google's servers when downloading the list of available images.


Some things to try:

- Refreshing your certificates: 

```sh 
sudo pip install certifi
```

- Try some of the suggestions here: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

**Comment by clgwlg** [comment]
this error is keeping me from using “sudo pip install certifi”, then I tried to add following code 
```python
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
```
this solution worked,Thanks!

**Comment by clgwlg** [comment]
Another exception occured:
ERROR:Failed to create default client, trying domain socket.
Traceback (most recent call last):
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/docker-4.2.0-py3.7.egg/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/docker-4.2.0-py3.7.egg/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/android-emulator-container-scripts-master/emu/docker_device.py", line 157, in get_api_client
    logging.info(api_client.version())
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/docker-4.2.0-py3.7.egg/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/docker-4.2.0-py3.7.egg/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/docker-4.2.0-py3.7.egg/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
ERROR:Failed to create container.
Traceback (most recent call last):
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/docker-4.2.0-py3.7.egg/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/urllib3-1.25.8-py3.7.egg/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/docker-4.2.0-py3.7.egg/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/android-emulator-container-scripts-master/emu/docker_device.py", line 172, in create_container
    api_client = self.get_api_client()
  File "/android-emulator-container-scripts-master/emu/docker_device.py", line 163, in get_api_client
    logging.info(api_client.version())
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/docker-4.2.0-py3.7.egg/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/docker-4.2.0-py3.7.egg/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/docker-4.2.0-py3.7.egg/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/android-emulator-container-scripts-master/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
WARNING:You can manually create the container as follows:
WARNING:docker build /android-emulator-container-scripts-master/src

**Comment by pokowaka** [comment]
This looks like a docker issue. You must have docker installed in order to create images.

Note that the image cannot be run under MacOS, as there is no hypervisor

**Comment by AkariIkenoue** [comment]
I got the same error message.
In my case, I tried just restart docker and it solved.
`systemctl start docker`

To contributors:
Thank you for such a useful script!

**Comment by siddhantsoni** [comment]
> ```python
> ```python
> import ssl
> 
> ssl._create_default_https_context = ssl._create_unverified_context
> ```
> 
> 
> this solution worked
> ```

This maybe a stupid question, but where do I add this code. Do you mean `setup.py`?

**Comment by siddhantsoni** [comment]
> this error is keeping me from using “sudo pip install certifi”, then I tried to add following code
> 
> ```python
> import ssl
> 
> ssl._create_default_https_context = ssl._create_unverified_context
> ```
> 
> this solution worked,Thanks!

This maybe a stupid question, but where do I add this code. Do you mean `setup.py`?

**Comment by pokowaka** [comment]
You should add it to this [emu/emu_docker.py](https://github.com/google/android-emulator-container-scripts/blob/a19eea26de24c83ada5582420d2c0b605b825568/emu/emu_docker.py).

**Comment by jpcottin** [comment]
Thanks for the report. The traceback here is from the old `urlfetch` HTTP library, which has since been replaced by `requests`, and the surface-level `interactive --start` build failures from this era have been addressed by #390. Closing as superseded — please open a fresh issue if you reproduce on current master.
