### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by goyourfly** [google/android-emulator-container-scripts#177]
While run `emu-docker interactive --start` get bellow exception
````
  Skipping already downloaded file: /home/zz/android-emulator-container-scripts/platform-tools-latest-linux.zip
Traceback (most recent call last):
  File "/home/zz/android-emulator-container-scripts/venv/bin/emu-docker", line 33, in <module>
    sys.exit(load_entry_point('emu-docker', 'console_scripts', 'emu-docker')())
  File "/home/zz/android-emulator-container-scripts/emu/emu_docker.py", line 271, in main
    args.func(args)
  File "/home/zz/android-emulator-container-scripts/emu/emu_docker.py", line 128, in create_docker_image_interactive
    device.create_docker_file(args.extra, metrics)
  File "/home/zz/android-emulator-container-scripts/emu/docker_device.py", line 277, in create_docker_file
    rename_as="README.MD",
  File "/home/zz/android-emulator-container-scripts/emu/template_writer.py", line 46, in write_template
    return self._write_template_to(template_file, os.path.join(self.dest, dest_name), template_dict)
  File "/home/zz/android-emulator-container-scripts/emu/template_writer.py", line 59, in _write_template_to
    dfile.write(template.render(template_dict))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 3635: ordinal not in range(128)
````

````
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zz/android-emulator-container-scripts/venv/lib/python3.5/site-packages/console_menu-0.6.0-py3.5.egg/consolemenu/console_menu.py", line 169, in _wrap_start
    self._main_loop()
  File "/home/zz/android-emulator-container-scripts/venv/lib/python3.5/site-packages/console_menu-0.6.0-py3.5.egg/consolemenu/console_menu.py", line 225, in _main_loop
    self.draw()
  File "/home/zz/android-emulator-container-scripts/venv/lib/python3.5/site-packages/console_menu-0.6.0-py3.5.egg/consolemenu/console_menu.py", line 233, in draw
    prologue_text=self.prologue_text, epilogue_text=self.epilogue_text))
  File "/home/zz/android-emulator-container-scripts/venv/lib/python3.5/site-packages/console_menu-0.6.0-py3.5.egg/consolemenu/screen.py", line 74, in printf
    print(*args, end='')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-77: ordinal not in range(128)
````

**Comment by AchrafAmil** [comment]
+1
I'm facing the same issue.

**Comment by AchrafAmil** [comment]
I can confirm @pokowaka's commit fixed the issue for me.
