### ISSUE TITLE
HTTP 500 Internal Error: no space on device issue?

### ISSUE THREAD

**Issue by Chineye-UTexas** [google/android-emulator-container-scripts#213]
When I try to build a new image, whether interactively or quick start I consistently get this error. This is brand new error, I have never had. I have tried to increase container base, I've removed dangling images and containers. Docker has plenty of space, any insight to what this may be?

```
Downloading system image: google_apis 29 Q x86_64 to /root/android-emulator-container-scripts/sys-img-google_apis-29-Q-x86_64.zip
  Skipping already downloaded file: /root/android-emulator-container-scripts/sys-img-google_apis-29-Q-x86_64.zip
Downloading emulator: stable 30.1.5 to /root/android-emulator-container-scripts/emulator-30.1.5.zip
  Skipping already downloaded file: /root/android-emulator-container-scripts/emulator-30.1.5.zip
Downloading platform tools to /root/android-emulator-container-scripts/platform-tools-latest-linux.zip
  Skipping already downloaded file: /root/android-emulator-container-scripts/platform-tools-latest-linux.zip
Extracting: /root/android-emulator-container-scripts/emulator-30.1.5.zip -> /root/android-emulator-container-scripts/src/emu
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 279/279 [00:05<00:00, 49.48it/s]
Extracting: /root/android-emulator-container-scripts/sys-img-google_apis-29-Q-x86_64.zip -> /root/android-emulator-container-scripts/src/sys
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:26<00:00,  1.16s/it]
Creating docker image: 29-google-x64:30.1.5.. be patient this can take a while!
ERROR:Failed to create container.
Traceback (most recent call last):
  File "/root/android-emulator-container-scripts/venv/lib/python3.6/site-packages/docker-4.2.2-py3.6.egg/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/root/android-emulator-container-scripts/venv/lib/python3.6/site-packages/requests-2.24.0-py3.6.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/build?t=29-google-x64%3A30.1.5&q=False&nocache=False&rm=True&forcerm=False&pull=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/android-emulator-container-scripts/emu/docker_device.py", line 182, in create_container
    for entry in result:
  File "/root/android-emulator-container-scripts/venv/lib/python3.6/site-packages/docker-4.2.2-py3.6.egg/docker/api/client.py", line 354, in _stream_helper
    yield self._result(response, json=decode)
  File "/root/android-emulator-container-scripts/venv/lib/python3.6/site-packages/docker-4.2.2-py3.6.egg/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/root/android-emulator-container-scripts/venv/lib/python3.6/site-packages/docker-4.2.2-py3.6.egg/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/root/android-emulator-container-scripts/venv/lib/python3.6/site-packages/docker-4.2.2-py3.6.egg/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Error processing tar file(exit status 1): write /emu/emulator/lib64/qt/libexec/icudtl.dat: no space left on device")
WARNING:You can manually create the container as follows:
WARNING:docker build /root/android-emulator-container-scripts/src
```

**Comment by Chineye-UTexas** [comment]
My var/df data folder on my system was full. pruning and removing old images helped.
