### ISSUE TITLE
jinjna2.exceptions.TemplateNotFound: emulator.README.MD

### ISSUE THREAD

**Issue by jkl334** [google/android-emulator-container-scripts#218]
I am running into some strange errors when running `emu-docker create` after cleaning up some docker resources on my machine:

```
Traceback (most recent call last):
  File "/usr/local/bin/emu-docker", line 33, in <module>
    sys.exit(load_entry_point('emu-docker==0+untagged.193.g45a5e5c', 'console_scripts', 'emu-docker')())
  File "/usr/local/lib/python3.6/dist-packages/emu_docker-0+untagged.193.g45a5e5c-py3.6.egg/emu/emu_docker.py", line 271, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/emu_docker-0+untagged.193.g45a5e5c-py3.6.egg/emu/emu_docker.py", line 99, in create_docker_image
    device.create_docker_file(args.extra, cfg.collect_metrics())
  File "/usr/local/lib/python3.6/dist-packages/emu_docker-0+untagged.193.g45a5e5c-py3.6.egg/emu/docker_device.py", line 277, in create_docker_file
    rename_as="README.MD",
  File "/usr/local/lib/python3.6/dist-packages/emu_docker-0+untagged.193.g45a5e5c-py3.6.egg/emu/template_writer.py", line 46, in write_template
    return self._write_template_to(template_file, os.path.join(self.dest, dest_name), template_dict)
  File "/usr/local/lib/python3.6/dist-packages/emu_docker-0+untagged.193.g45a5e5c-py3.6.egg/emu/template_writer.py", line 55, in _write_template_to
    template = self.env.get_template(tmpl_file)
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-2.11.1-py3.6.egg/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-2.11.1-py3.6.egg/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-2.11.1-py3.6.egg/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-2.11.1-py3.6.egg/jinja2/loaders.py", line 299, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: emulator.README.MD
```

any insight here would be much appreciated

**Comment by pokowaka** [comment]
We did not update the setup.py to install the template, causing this issue. Fix incoming.
