### ISSUE TITLE
issue with .configure.sh

### ISSUE THREAD

**Issue by ydonev** [google/android-emulator-container-scripts#258]
OS:
```
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.3:GA:server
Kernel: Linux 3.10.0-957.5.1.el7.x86_64
```

Issue:
`[17:41][user@rhel-vm][~/androidEmu/android-emulator-container-scripts]% source ./configure.sh
running develop
running egg_info
writing requirements to emu_docker.egg-info/requires.txt
writing emu_docker.egg-info/PKG-INFO
writing top-level names to emu_docker.egg-info/top_level.txt
writing entry points to emu_docker.egg-info/entry_points.txt
writing dependency_links to emu_docker.egg-info/dependency_links.txt
reading manifest file 'emu_docker.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'emu_docker.egg-info/SOURCES.txt'
running build_ext
Creating /home/user/androidEmu/android-emulator-container-scripts/venv/lib/python3.4/site-packages/emu-docker.egg-link (link to .)
emu-docker 0+untagged.280.g318c3c2 is already the active version in easy-install.pth
Installing emu-docker script to /home/user/androidEmu/android-emulator-container-scripts/venv/bin

Installed /home/user/androidEmu/android-emulator-container-scripts
Processing dependencies for emu-docker==0+untagged.280.g318c3c2
Searching for MarkupSafe>=0.23
Reading https://pypi.org/simple/MarkupSafe/
Downloading https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz#sha256=594c67807fb16238b30c44bdf74f36c02cdf22d1c8cda91ef8a0ed8dabf5620a
Best match: MarkupSafe 2.0.1
Processing MarkupSafe-2.0.1.tar.gz
Writing /tmp/easy_install-q0gce0fr/MarkupSafe-2.0.1/setup.cfg
Running MarkupSafe-2.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-q0gce0fr/MarkupSafe-2.0.1/egg-dist-tmp-qx_1q9sz
Traceback (most recent call last):
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-q0gce0fr/MarkupSafe-2.0.1/setup.py", line 61, in <module>
    long_description_content_type="text/markdown",  # Optional (see note above)
  File "/tmp/easy_install-q0gce0fr/MarkupSafe-2.0.1/setup.py", line 44, in run_setup
    version=versioneer.get_version(),
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.4/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/dist.py", line 702, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 349, in _parse_attr
    module = import_module(module_name)
  File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/tmp/easy_install-q0gce0fr/MarkupSafe-2.0.1/src/markupsafe/__init__.py", line 112
    return f"{self.__class__.__name__}({super().__repr__()})"
                                                            ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 178, in <module>
    "Source": "https://github.com/google/android-emulator-container-scripts",
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/command/develop.py", line 156, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib64/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib64/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-q0gce0fr/MarkupSafe-2.0.1/setup.py", line 61, in <module>
    long_description_content_type="text/markdown",  # Optional (see note above)
  File "/tmp/easy_install-q0gce0fr/MarkupSafe-2.0.1/setup.py", line 44, in run_setup
    version=versioneer.get_version(),
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.4/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/dist.py", line 702, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/setuptools/config.py", line 349, in _parse_attr
    module = import_module(module_name)
  File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/tmp/easy_install-q0gce0fr/MarkupSafe-2.0.1/src/markupsafe/__init__.py", line 112
    return f"{self.__class__.__name__}({super().__repr__()})"
                                                            ^
SyntaxError: invalid syntax
Ready to run emu-docker!`

`emu-docker --version
Traceback (most recent call last):
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/bin/emu-docker", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/user/androidEmu/android-emulator-container-scripts/venv/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'MarkupSafe>=0.23' distribution was not found and is required by jinja2`

**Comment by pokowaka** [comment]
Looks like we might have to pin the version to something like '2.0.0a1'

**Comment by jpcottin** [comment]
RHEL 7.3 is from 2016 and the RHEL 7 line as a whole reached EOL on 2024-06-30. `configure.sh` has been updated several times since the report. Closing as obsolete — please open a fresh issue if you reproduce on a supported distro release.
