### ISSUE TITLE
Error when trying to create container using `emu-docker`

### ISSUE THREAD

**Issue by RobsonAraujoValidity** [google/android-emulator-container-scripts#261]
I've followed all steps to install all dependencies on a new Ubuntu 20.04 VM (Python, KVM, Docker SUDOLESS, Docker Compose, NodeJS, NPM), and when trying to use emu-docker to create a new image (using `emu-docker interactive --start` or `emu-docker create stable "S.*x86_64"` I'm getting the same error:

```
Downloading emulator: stable 30.7.5 to /home/robson/android-emulator-container-scripts/emulator-30.7.5.zip
  Skipping already downloaded file: /home/robson/android-emulator-container-scripts/emulator-30.7.5.zip
Traceback (most recent call last):
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/urllib3-1.26.6-py3.8.egg/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/urllib3-1.26.6-py3.8.egg/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/docker-5.0.0-py3.8.egg/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/urllib3-1.26.6-py3.8.egg/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/urllib3-1.26.6-py3.8.egg/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/urllib3-1.26.6-py3.8.egg/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/urllib3-1.26.6-py3.8.egg/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/urllib3-1.26.6-py3.8.egg/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/docker-5.0.0-py3.8.egg/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/docker-5.0.0-py3.8.egg/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/docker-5.0.0-py3.8.egg/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/docker-5.0.0-py3.8.egg/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/docker-5.0.0-py3.8.egg/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/requests-2.25.1-py3.8.egg/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robson/android-emulator-container-scripts/venv/bin/emu-docker", line 33, in <module>
    sys.exit(load_entry_point('emu-docker', 'console_scripts', 'emu-docker')())
  File "/home/robson/android-emulator-container-scripts/emu/emu_docker.py", line 300, in main
    args.func(args)
  File "/home/robson/android-emulator-container-scripts/emu/emu_docker.py", line 129, in create_docker_image_interactive
    if not sys_docker.available() and not sys_docker.can_pull():
  File "/home/robson/android-emulator-container-scripts/emu/containers/docker_container.py", line 219, in available
    return self.docker_image() != None
  File "/home/robson/android-emulator-container-scripts/emu/containers/docker_container.py", line 210, in docker_image
    client = self.get_client()
  File "/home/robson/android-emulator-container-scripts/emu/containers/docker_container.py", line 82, in get_client
    return docker.from_env()
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/docker-5.0.0-py3.8.egg/docker/client.py", line 96, in from_env
    return cls(
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/docker-5.0.0-py3.8.egg/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/docker-5.0.0-py3.8.egg/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/robson/android-emulator-container-scripts/venv/lib/python3.8/site-packages/docker-5.0.0-py3.8.egg/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

Any thoughts of where I'm messing up?

**Comment by RobsonAraujoValidity** [comment]
Well, I was really messing up. Docker daemon was not started.
