### ISSUE TITLE
Adding support for android-automotive image

### ISSUE THREAD

**Issue by insyncim64** [google/android-emulator-container-scripts#286]
Hi,
it looks like this project can not support system image of Android Automotive now. 
It throws following exception, when the system image is for Android Automotive.
Traceback (most recent call last):
  File "/home/jou1/Development/android-emulator-container-scripts/venv/bin/emu-docker", line 33, in <module>
    sys.exit(load_entry_point('emu-docker', 'console_scripts', 'emu-docker')())
  File "/home/jou1/Development/android-emulator-container-scripts/emu/emu_docker.py", line 300, in main
    args.func(args)
  File "/home/jou1/Development/android-emulator-container-scripts/emu/emu_docker.py", line 87, in create_docker_image
    sys_docker = SystemImageContainer(img, args.repo)
  File "/home/jou1/Development/android-emulator-container-scripts/emu/containers/system_image_container.py", line 34, in __init__
    self.system_image_zip = SystemImageReleaseZip(sort)
  File "/home/jou1/Development/android-emulator-container-scripts/emu/android_release_zip.py", line 128, in __init__
    self.props["qemu.short_tag"] = self.short_tag()
  File "/home/jou1/Development/android-emulator-container-scripts/emu/android_release_zip.py", line 168, in short_tag
    return self.SHORT_TAG[self.tag()]
KeyError: 'android-automotive'

**Comment by grossamos** [comment]
Facing the same issue, are there any updates on this?
(using images: https://dl.google.com/android/repository/sys-img/android-automotive/x86_64-30_r02.zip and https://developer.polestar.com/sdk/polestar_emulator_v29.zip)

**Comment by gogamid** [comment]
interested

**Comment by daniyalsyed** [comment]
Stuck at this point, using Android automotive image.

**Comment by nahshal** [comment]
I'm also interested, I could run the Emulator for Android but not for Automotive, any Update here?

**Comment by 3ss-rglas** [comment]
3 years and still not working
