### ISSUE TITLE
Error while building images : KeyError: 'ro.product.cpu.abi'

### ISSUE THREAD

**Issue by Vefine596** [google/android-emulator-container-scripts#293]
Hi,

I'm trying to build an image with the command 
```bash
emu-docker interactive

>> System image: 54 - 31 S google_apis (x86_64)
>> Emulator: 2 - EMU stable 31.2.6
```

But it ends with this error : 
```bash
docker build /root/android-emulator-container-scripts/src -t us-docker.pkg.dev/android-emulator-268719/images/sys-31-google-x64:7818354
Step 1/14 : FROM alpine:3.3 AS unzipper
 ---> a6fc1dbfa81a
Step 2/14 : RUN apk add --update unzip
 ---> Running in 4aa6d2260570
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/1) Installing unzip (6.0-r1)
Executing busybox-1.24.2-r2.trigger
OK: 5 MiB in 12 packages
Removing intermediate container 4aa6d2260570
 ---> 164cb80ff9d5
Step 3/14 : FROM unzipper as sys_unzipper
 ---> 164cb80ff9d5
Step 4/14 : COPY sys-img-google_apis-31-S-x86_64.zip /tmp/
 ---> 5efe35e49cd1
Step 5/14 : RUN unzip -u -o /tmp/sys-img-google_apis-31-S-x86_64.zip -d /sysimg/
 ---> Running in 01cd9bcfd6b7
Archive:  /tmp/sys-img-google_apis-31-S-x86_64.zip
  inflating: /sysimg/x86_64/VerifiedBootParams.textproto  
  inflating: /sysimg/x86_64/advancedFeatures.ini  
  inflating: /sysimg/x86_64/build.prop  
  inflating: /sysimg/x86_64/encryptionkey.img  
  inflating: /sysimg/x86_64/kernel-ranchu  
  inflating: /sysimg/x86_64/ramdisk.img  
  inflating: /sysimg/x86_64/source.properties  
  inflating: /sysimg/x86_64/system.img  
  inflating: /sysimg/x86_64/userdata.img  
  inflating: /sysimg/x86_64/vendor.img  
 extracting: /sysimg/x86_64/data/local.prop  
  inflating: /sysimg/x86_64/data/misc/apns/apns-conf.xml  
  inflating: /sysimg/x86_64/data/misc/emulator/version.txt  
  inflating: /sysimg/x86_64/data/misc/emulator/config/radioconfig.xml  
  inflating: /sysimg/x86_64/data/misc/gceconfigs/gpu.config  
  inflating: /sysimg/x86_64/data/misc/modem_simulator/iccprofile_for_carrierapitests.xml  
  inflating: /sysimg/x86_64/data/misc/modem_simulator/iccprofile_for_sim0.xml  
  inflating: /sysimg/x86_64/data/misc/modem_simulator/etc/modem_simulator/files/numeric_operator.xml  
Traceback (most recent call last):
  File "/root/android-emulator-container-scripts/venv/bin/emu-docker", line 33, in <module>
    sys.exit(load_entry_point('emu-docker', 'console_scripts', 'emu-docker')())
  File "/root/android-emulator-container-scripts/emu/emu_docker.py", line 300, in main
    args.func(args)
  File "/root/android-emulator-container-scripts/emu/emu_docker.py", line 132, in create_docker_image_interactive
    emu_docker = EmulatorContainer(emu_zip, sys_docker, args.repo, metrics)
  File "/root/android-emulator-container-scripts/emu/containers/emulator_container.py", line 41, in __init__
    cpu = system_image_container.image_labels()["ro.product.cpu.abi"]
KeyError: 'ro.product.cpu.abi'

```

Debian 10 (buster)
Kernel: 4.19.0-18-amd64
Docker version 20.10.12, build e91ed57
User: root
android-emulator-container-scripts: master

**Comment by Vefine596** [comment]
Sorry, the reason was a "no space left on device", but this message error was not shown in interactive mode...
