### ISSUE TITLE
error docker-emu

### ISSUE THREAD

**Issue by zhinea** [google/android-emulator-container-scripts#320]
logs
```
Traceback (most recent call last):
  File "/home/zidna/android-emulator-container-scripts/venv/bin/emu-docker", line 33, in <module>
    sys.exit(load_entry_point('emu-docker', 'console_scripts', 'emu-docker')())
  File "/home/zidna/android-emulator-container-scripts/venv/bin/emu-docker", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/zidna/android-emulator-container-scripts/venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zidna/android-emulator-container-scripts/emu/emu_docker.py", line 28, in <module>
    import emu.emu_downloads_menu as emu_downloads_menu
  File "/home/zidna/android-emulator-container-scripts/emu/emu_downloads_menu.py", line 25, in <module>
    import requests
  File "/home/zidna/android-emulator-container-scripts/venv/lib/python3.6/site-packages/requests-2.28.1-py3.6.egg/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/zidna/android-emulator-container-scripts/venv/lib/python3.6/site-packages/urllib3-2.0.0a2-py3.6.egg/urllib3/__init__.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

python version: Python 3.6.9
ubuntu 18lts

**Comment by grossamos** [comment]
Had a simmilar issues with some of the dependencies. Potentially try:

```bash
source configure.sh
pip install --force-reinstall -v "idna==3"
pip install --force-reinstall -v "charset-normalizer==2"
pip install --force-reinstall -v "urllib3==1.26"
pip install --force-reinstall -v "charset-markupsafe==2.0.1"
source configure.sh
emu-docker -h
```

**Comment by grossamos** [comment]
Also is `source configure.sh` throwing an error like this?

```
error: urllib3 2.0.0a3 is installed but urllib3<1.27,>=1.21.1 is required by {'requests'}
```

**Comment by Th3C0D3R** [comment]
> Also is `source configure.sh` throwing an error like this?
> 
> 
> 
> ```
> 
> error: urllib3 2.0.0a3 is installed but urllib3<1.27,>=1.21.1 is required by {'requests'}
> 
> ```

I have the same problem... unable to fix it currently

**Comment by grossamos** [comment]
@Th3C0D3R have you attempted to run the commands I provided above?

**Comment by Th3C0D3R** [comment]
> @Th3C0D3R have you attempted to run the commands I provided above?

Yes, did not work. I will try again and send the result

**Comment by Th3C0D3R** [comment]
ok now it worked, but I have now a different problem xD

![grafik](https://user-images.githubusercontent.com/7798500/213995065-9e91cfd0-9900-4553-912c-eea2a122408a.png)

**Comment by mcknly** [comment]
> Had a simmilar issue with some of the dependencies. Potentially try:
> 
> ```shell
> source configure.sh
> pip install --force-reinstall -v "idna==3"
> pip install --force-reinstall -v "charset-normalizer==2"
> pip install --force-reinstall -v "urllib3==1.26"
> pip install --force-reinstall -v "markupsafe==2.0.1"
> source configure.sh
> emu-docker -h
> ```

Same issue, and this worked for me.

**Comment by jpcottin** [comment]
Closing as stale. The 2022 Traceback was from a now-superseded install/Python state. The package has been substantially overhauled since (Poetry, Python ^3.10+) and the `emu-docker` entry point + supporting modules look completely different on current `master`.

If `emu-docker -h` or `emu-docker <command>` errors on current `master` (Python 3.10+, fresh install via `pip install -e .` or Poetry), please open a new issue with the current Traceback — the code has changed substantially since this was filed, so a fresh thread will be easier to track.
