### ISSUE TITLE
Error install emu-docker with ubuntu-pro-1804-bionic-v20230522 in GCE

### ISSUE THREAD

**Issue by ngonhat94** [google/android-emulator-container-scripts#346]
Obtaining file:///home/cloudemulator23/android-emulator-container-scripts
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/cloudemulator23/android-emulator-container-scripts/.venv/bin/python3 /home/cloudemulator23/android-emulator-container-scripts/.venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_editable /tmp/tmpoide3q1k
       cwd: /home/cloudemulator23/android-emulator-container-scripts
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/home/cloudemulator23/android-emulator-container-scripts/.venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/cloudemulator23/android-emulator-container-scripts/.venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/cloudemulator23/android-emulator-container-scripts/.venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 191, in prepare_metadata_for_build_editable
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-prpba57c/overlay/lib/python3.6/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
      poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
    File "/tmp/pip-build-env-prpba57c/overlay/lib/python3.6/site-packages/poetry/core/factory.py", line 43, in create_poetry
      raise RuntimeError("The Poetry configuration is invalid:\n" + message)
  RuntimeError: The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  
  ----------------------------------------
WARNING: Discarding file:///home/cloudemulator23/android-emulator-container-scripts. Command errored out with exit status 1: /home/cloudemulator23/android-emulator-container-scripts/.venv/bin/python3 /home/cloudemulator23/android-emulator-container-scripts/.venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_editable /tmp/tmpoide3q1k Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/cloudemulator23/android-emulator-container-scripts/.venv/bin/python3 /home/cloudemulator23/android-emulator-container-scripts/.venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_editable /tmp/tmpoide3q1k Check the logs for full command output.
Ready to run emu-docker!

**Comment by anamhira47** [comment]
I am having the same issue

**Comment by rossanoua** [comment]
any update?

**Comment by YogiDwiAndrian** [comment]
I am having the same issue

**Comment by YogiDwiAndrian** [comment]
i solved the problem by upgrade my python version to 3.10.13

I found out that the minimum version is 3.8. something, because I forgot the exact version for minimum

**Comment by jpcottin** [comment]
Ubuntu 18.04 has been EOL since 2023-06 and the install-time errors here are tied to that distro's pip toolchain. Closing as obsolete — please open a fresh issue if you reproduce on a supported Ubuntu release.
