### ISSUE TITLE
Not able to view the emualtor on the web browser

### ISSUE THREAD

**Issue by hridhar** [google/android-emulator-container-scripts#383]
Hi,

Please help and support.

Please find the below information.
We are able to list the services using below command.
grpcurl -plaintext localhost:8554 list

We are using the below scripts to run the emulator over container.
https://github.com/google/android-emulator-container-scripts

We are fallowing below steps.

git clone https://github.com/google/android-emulator-container-scripts.git
cd android-emulator-container-script
source ./configure.sh
emu-docker licenses
emu-docker create /path/to/emulator.zip /path/to/system-image.zip
/create_web_container.sh
docker-compose -f js/docker/docker-compose-build.yaml -f js/docker/development.yaml up
Expected Result:
8.Emulator should run without any issue over web browser.
Point your browser to [localhost](http://localhost/).

Actual Result:
8. Not able to view the emulator on the web browser.

Error Facing:
We are able to print the token also.

Below is the trace logs.
POST http://localhost:8080/android.emulation.control.EmulatorController/sendMouse 401 (Unauthorized)
Ot @ index.js:42
Yt @ index.js:63
(anonymous) @ index.js:57
Kt.X @ index.js:57
(anonymous) @ emulator_web_client.js:68
i.android.emulation.control.EmulatorControllerClient.sendMouse @ emulator_controller_grpc_web_pb.js:742
value @ jsep_protocol_driver.js:351
(anonymous) @ event_handler.js:101
gi @ react-dom.production.min.js:131
ys @ react-dom.production.min.js:220
Pl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Go @ react-dom.production.min.js:122
xl @ react-dom.production.min.js:252
vl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Go @ react-dom.production.min.js:122
qo @ react-dom.production.min.js:123
Yo @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Nr @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
$t @ react-dom.production.min.js:73
emulator_web_client.js:94 low level gRPC error: {"message":"Http response at 400 or 500 level, http status code: 401","stack":"Error: Http response at 400 or 500 level, http status code: 401\n at new k ([http://localhost/static/js/main.9d8095e4.js:2:742097)\n](http://localhost/static/js/main.9d8095e4.js:2:742097)%5Cn) at Gt ([http://localhost/static/js/main.9d8095e4.js:2:765119)\n](http://localhost/static/js/main.9d8095e4.js:2:765119)%5Cn) at Ct. ([http://localhost/static/js/main.9d8095e4.js:2:764803)\n](http://localhost/static/js/main.9d8095e4.js:2:764803)%5Cn) at ze ([http://localhost/static/js/main.9d8095e4.js:2:751021)\n](http://localhost/static/js/main.9d8095e4.js:2:751021)%5Cn) at Ve ([http://localhost/static/js/main.9d8095e4.js:2:750827)\n](http://localhost/static/js/main.9d8095e4.js:2:750827)%5Cn) at xt ([http://localhost/static/js/main.9d8095e4.js:2:758352)\n](http://localhost/static/js/main.9d8095e4.js:2:758352)%5Cn) at Pt ([http://localhost/static/js/main.9d8095e4.js:2:759133)\n](http://localhost/static/js/main.9d8095e4.js:2:759133)%5Cn) at r.W ([http://localhost/static/js/main.9d8095e4.js:2:760075)\n](http://localhost/static/js/main.9d8095e4.js:2:760075)%5Cn) at r.R ([http://localhost/static/js/main.9d8095e4.js:2:760054)","code":16,"metadata":{}}](http://localhost/static/js/main.9d8095e4.js:2:760054)%22,%22code%22:16,%22metadata%22:%7B%7D%7D)

We have tried opening http://localhost:8080/android.emulation.control.EmulatorController/sendMouse over the web browser.
Getting below error:
Jwt is missing

Below is the response header:
Access-Control-Allow-Origin : http://localhost/
Access-Control-Expose-Headers : custom-header-1,grpc-status,grpc-message
Connection : close
Content-Length : 0
Content-Type : application/grpc-web-text+proto
Date : Wed, 24 Jul 2024 13:49:36 GMT
Grpc-Message : Jwks remote fetch is failed
Grpc-Status : 16
Server : envoy
Www-Authenticate : Bearer realm="http://localhost:8080/android.emulation.control.EmulatorController/getStatus", error="invalid_token"

Below is the request header:
Accept : application/grpc-web-text
Accept-Encoding : gzip, deflate, br, zstd
Accept-Language : en-US,en;q=0.9
Authorization : Bearer "TOKEN KEY"
Connection : keep-alive
Content-Length : 8
Content-Type : application/grpc-web-text
Dnt : 1
Host : localhost:8080
Origin : http://localhost/
Referer : http://localhost/
Sec-Ch-Ua : "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126"
Sec-Ch-Ua-Mobile : ?0
Sec-Ch-Ua-Platform : "Linux"
Sec-Fetch-Dest : empty
Sec-Fetch-Mode : cors
Sec-Fetch-Site : same-site
User-Agent : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
X-Grpc-Web : 1
X-User-Agent : grpc-web-javascript/0.1

General Information:
Request URL : http://localhost:8080/android.emulation.control.EmulatorController/getStatus
Request Method : POST
Status Code : 401 Unauthorized
Remote Address : [::1]:8080
Referrer Policy : strict-origin-when-cross-origin

We are able to print the token below:
if (isSignedIn) {
firebase.auth().currentUser.getIdToken().then(function (token) {
auth.setToken(Bearer ${token});
console.log("Token in authHeader:", token);
});
}

/**

Called by the EmulatorWebClient to obtain the authentication
headers
@memberof TokenAuthService
@returns The authentication header for the web call
https://github.com/see EmulatorWebClient
*/
authHeader = () => {
console.log("Token in authHeader:", this.token );
return { Authorization: this.token };
};
}

Please let me know if you need some more information.
Thank for the support, much appreciated.

**Comment by hridhar** [comment]
<HTML><HEAD>
			<TITLE>Web Site does not exist</TITLE>
			<link rel="shortcut icon" href="https://rbins.bosch.com/gfx/favicon.ico">
			<link rel="stylesheet" href="https://rbins.bosch.com/gfx/styles.css">
		</HEAD>
		<BODY>
		    <table>
		        <TR>
		            <td width="128" ><img height=31 src=https://rbins.bosch.com/gfx/bosch_logo.png alt=BOSCH></td>
				    <td width="700" align="center"><h1 class="errorsum_header">Web Site does not exist</h1></td>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700" align="center" ><table border=1 width=600px ><tr style=font-size:30px align=center ><td bgcolor=green></td><td bgcolor=green>&#x1F44C;</td><td bgcolor=red>&#x2049;</td></tr><tr style=font-size:70px align=center><td bgcolor=green>&#x1F615;</td><td bgcolor=green>&#x1F5A5;</td><td bgcolor=red>&#x1F310;</td></tr><tr style=font-size:40px align=center><td bgcolor=green>You</td><td bgcolor=green>Proxy</td><td bgcolor=red>WWW</td></tr><tr style=font-size:11px align=center><td>10.165.193.0<br>APAC\bvsa1kor</td><td>2024-07-29 - 12:19:37 (GMT)<br>in2psg03: dns_unresolved_hostname</td><td>http://curl ()<br>none (6/10)</td></tr></table></TD>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700"><BR><BR><BR><BR><FONT face="Helvetica" SIZE=3><b>curl</b> does not exist inside or outside of Bosch.<BR><BR>You can try:<BR><li>Reloading the page after a few minutes.<li>Check your URL for spelling error.<li>Check with website owner support<BR><BR>If this is our own web site you should report it to your servicedesk. </FONT><BR><BR><BR><BR></td>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700">
                        <table valign=top>
                        <tr>
                            <td>If you need support:<br>&nbsp;</td>
                        </tr>
                        <tr>
                            <td width=350><img height=31 src=https://rbins.bosch.com/gfx/bosch_logo.png alt=BOSCH></td>
                            <td width=350><img height=31 src=https://rbins.bosch.com/gfx/bsh-logo.png alt=B/S/H/></td>
                        </tr>
                        <tr>
                            <td valign=top><p>E-mail: <a href=mailto:ITServiceDesk%40de.bosch.com>ITServiceDesk@de.bosch.com</a></p><p>Phone: +49 (711) 811 3311</p></td><td valign=top><p>E-mail: <a href=mailto:servicedesk@bshg.com>BSH Service Desk</a></p><p>Phone: +48 (42) 274 4444 (or the local speed dial number)</p></td>
                        </tr>
                        </table>
                    </TD>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700"><hr>Technical information for support:<BR>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700" FONT face="Helvetica" SIZE=2><BR>
                            <b>Web Site does not exist (dns_unresolved_hostname)</b><BR><BR>
    						<b>User:</b> APAC\bvsa1kor<BR>		 
    						<b>URL:</b> http:&#x2F;&#x2F;curl&#x2F;<BR><BR>
    						<b>Category(ies):</b> none<BR>
    						<b>Risk level:</b> 6/10<BR>
    						<b>Proxy:</b> in2psg03<BR>
    						<b>Client Address:</b> 10.165.193.0<BR>
    						<b>Destination Address:</b> <BR>
    						<b>Time:</b> (GMT) 2024-07-29 12:19:37<BR>
    						<b>Policy:</b> NC<BR>
    					</FONT></TD>
		        </TR>
		    </table>
		</BODY>
	</HTML>

**Comment by hridhar** [comment]
<HTML><HEAD>
			<TITLE>Web Site does not exist</TITLE>
			<link rel="shortcut icon" href="https://rbins.bosch.com/gfx/favicon.ico">
			<link rel="stylesheet" href="https://rbins.bosch.com/gfx/styles.css">
		</HEAD>
		<BODY>
		    <table>
		        <TR>
		            <td width="128" ><img height=31 src=https://rbins.bosch.com/gfx/bosch_logo.png alt=BOSCH></td>
				    <td width="700" align="center"><h1 class="errorsum_header">Web Site does not exist</h1></td>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700" align="center" ><table border=1 width=600px ><tr style=font-size:30px align=center ><td bgcolor=green></td><td bgcolor=green>&#x1F44C;</td><td bgcolor=red>&#x2049;</td></tr><tr style=font-size:70px align=center><td bgcolor=green>&#x1F615;</td><td bgcolor=green>&#x1F5A5;</td><td bgcolor=red>&#x1F310;</td></tr><tr style=font-size:40px align=center><td bgcolor=green>You</td><td bgcolor=green>Proxy</td><td bgcolor=red>WWW</td></tr><tr style=font-size:11px align=center><td>10.165.193.0<br>APAC\bvsa1kor</td><td>2024-07-29 - 12:19:37 (GMT)<br>in2psg03: dns_unresolved_hostname</td><td>http://curl ()<br>none (6/10)</td></tr></table></TD>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700"><BR><BR><BR><BR><FONT face="Helvetica" SIZE=3><b>curl</b> does not exist inside or outside of Bosch.<BR><BR>You can try:<BR><li>Reloading the page after a few minutes.<li>Check your URL for spelling error.<li>Check with website owner support<BR><BR>If this is our own web site you should report it to your servicedesk. </FONT><BR><BR><BR><BR></td>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700">
                        <table valign=top>
                        <tr>
                            <td>If you need support:<br>&nbsp;</td>
                        </tr>
                        <tr>
                            <td width=350><img height=31 src=https://rbins.bosch.com/gfx/bosch_logo.png alt=BOSCH></td>
                            <td width=350><img height=31 src=https://rbins.bosch.com/gfx/bsh-logo.png alt=B/S/H/></td>
                        </tr>
                        <tr>
                            <td valign=top><p>E-mail: <a href=mailto:ITServiceDesk%40de.bosch.com>ITServiceDesk@de.bosch.com</a></p><p>Phone: +49 (711) 811 3311</p></td><td valign=top><p>E-mail: <a href=mailto:servicedesk@bshg.com>BSH Service Desk</a></p><p>Phone: +48 (42) 274 4444 (or the local speed dial number)</p></td>
                        </tr>
                        </table>
                    </TD>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700"><hr>Technical information for support:<BR>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700" FONT face="Helvetica" SIZE=2><BR>
                            <b>Web Site does not exist (dns_unresolved_hostname)</b><BR><BR>
    						<b>User:</b> APAC\bvsa1kor<BR>		 
    						<b>URL:</b> http:&#x2F;&#x2F;curl&#x2F;<BR><BR>
    						<b>Category(ies):</b> none<BR>
    						<b>Risk level:</b> 6/10<BR>
    						<b>Proxy:</b> in2psg03<BR>
    						<b>Client Address:</b> 10.165.193.0<BR>
    						<b>Destination Address:</b> <BR>
    						<b>Time:</b> (GMT) 2024-07-29 12:19:37<BR>
    						<b>Policy:</b> NC<BR>
    					</FONT></TD>
		        </TR>
		    </table>
		</BODY>
	</HTML>

**Comment by hridhar** [comment]
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="/favicon.ico"/><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500"/><link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><meta name="theme-color" content="#000000"/><link rel="manifest" href="/manifest.json"/><title>React App</title><script defer="defer" src="/static/js/main.84b0fe95.js"></script><link href="/static/css/main.4c7bd351.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>

**Comment by hridhar** [comment]
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="/favicon.ico"/><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500"/><link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><meta name="theme-color" content="#000000"/><link rel="manifest" href="/manifest.json"/><title>React App</title><script defer="defer" src="/static/js/main.84b0fe95.js"></script><link href="/static/css/main.4c7bd351.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>

**Comment by hridhar** [comment]
<HTML><HEAD>
			<TITLE>Web Site does not exist</TITLE>
			<link rel="shortcut icon" href="https://rbins.bosch.com/gfx/favicon.ico">
			<link rel="stylesheet" href="https://rbins.bosch.com/gfx/styles.css">
		</HEAD>
		<BODY>
		    <table>
		        <TR>
		            <td width="128" ><img height=31 src=https://rbins.bosch.com/gfx/bosch_logo.png alt=BOSCH></td>
				    <td width="700" align="center"><h1 class="errorsum_header">Web Site does not exist</h1></td>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700" align="center" ><table border=1 width=600px ><tr style=font-size:30px align=center ><td bgcolor=green></td><td bgcolor=green>&#x1F44C;</td><td bgcolor=red>&#x2049;</td></tr><tr style=font-size:70px align=center><td bgcolor=green>&#x1F615;</td><td bgcolor=green>&#x1F5A5;</td><td bgcolor=red>&#x1F310;</td></tr><tr style=font-size:40px align=center><td bgcolor=green>You</td><td bgcolor=green>Proxy</td><td bgcolor=red>WWW</td></tr><tr style=font-size:11px align=center><td>10.165.199.187<br>APAC\bvsa1kor</td><td>2024-08-13 - 13:14:54 (GMT)<br>in2psg04: dns_unresolved_hostname</td><td>http://docker_front-envoy_1 ()<br>none (none/10)</td></tr></table></TD>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700"><BR><BR><BR><BR><FONT face="Helvetica" SIZE=3><b>docker_front-envoy_1</b> does not exist inside or outside of Bosch.<BR><BR>You can try:<BR><li>Reloading the page after a few minutes.<li>Check your URL for spelling error.<li>Check with website owner support<BR><BR>If this is our own web site you should report it to your servicedesk. </FONT><BR><BR><BR><BR></td>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700">
                        <table valign=top>
                        <tr>
                            <td>If you need support:<br>&nbsp;</td>
                        </tr>
                        <tr>
                            <td width=350><img height=31 src=https://rbins.bosch.com/gfx/bosch_logo.png alt=BOSCH></td>
                            <td width=350><img height=31 src=https://rbins.bosch.com/gfx/bsh-logo.png alt=B/S/H/></td>
                        </tr>
                        <tr>
                            <td valign=top><p>E-mail: <a href=mailto:ITServiceDesk%40de.bosch.com>ITServiceDesk@de.bosch.com</a></p><p>Phone: +49 (711) 811 3311</p></td><td valign=top><p>E-mail: <a href=mailto:servicedesk@bshg.com>BSH Service Desk</a></p><p>Phone: +48 (42) 274 4444 (or the local speed dial number)</p></td>
                        </tr>
                        </table>
                    </TD>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700"><hr>Technical information for support:<BR>
		        </TR>
		        <TR>
		            <TD width="128"></TD>
                    <TD width="700" FONT face="Helvetica" SIZE=2><BR>
                            <b>Web Site does not exist (dns_unresolved_hostname)</b><BR><BR>
    						<b>User:</b> APAC\bvsa1kor<BR>		 
    						<b>URL:</b> http:&#x2F;&#x2F;docker_front-envoy_1:8080&#x2F;<BR><BR>
    						<b>Category(ies):</b> none<BR>
    						<b>Risk level:</b> none/10<BR>
    						<b>Proxy:</b> in2psg04<BR>
    						<b>Client Address:</b> 10.165.199.187<BR>
    						<b>Destination Address:</b> <BR>
    						<b>Time:</b> (GMT) 2024-08-13 13:14:54<BR>
    						<b>Policy:</b> NC<BR>
    					</FONT></TD>
		        </TR>
		    </table>
		</BODY>
	</HTML>

**Comment by jpcottin** [comment]
Duplicate of #370 (same title, same author, same symptoms). Closing this one to consolidate; please follow #370 for any updates.
