### ISSUE TITLE
Unable to run `emu-docker create` successfully

### ISSUE THREAD

**Issue by li-richard** [google/android-emulator-container-scripts#9]
I tried with both Python 2.7 and 3.6.8

with 2.7, the error I get is:
```
Traceback (most recent call last):
  File "./emu/emu_docker.py", line 191, in <module>
    main()
  File "./emu/emu_docker.py", line 184, in main
    args.func(args)
  File "./emu/emu_docker.py", line 125, in create_docker_image
    create_docker(args.dest, args.emuzip, args.imgzip, args.repo, args.extra)
  File "./emu/emu_docker.py", line 45, in create_docker
    mkdir_p(src_dir)
  File "./emu/emu_docker.py", line 31, in mkdir_p
    os.makedirs(path, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```
which seems like an issue with python3 compatibility

with 3.6.8, the error i get is:
```
Copying zips to docker src dir: /home/<user>/android-emulator-container-scripts/src
Traceback (most recent call last):
  File "./emu/emu_docker.py", line 191, in <module>
    main()
  File "./emu/emu_docker.py", line 184, in main
    args.func(args)
  File "./emu/emu_docker.py", line 125, in create_docker_image
    create_docker(args.dest, args.emuzip, args.imgzip, args.repo, args.extra)
  File "./emu/emu_docker.py", line 69, in create_docker
    shutil.copy2(adb_loc, platform_tools_dir)
  File "/usr/lib64/python3.6/shutil.py", line 262, in copy2
    dst = os.path.join(dst, os.path.basename(src))
  File "/usr/lib64/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by li-richard** [comment]
nvm, didnt have adb on the path

**Comment by pokowaka** [comment]
Please try the updated version, if you run into issues, could you please share the logs from running:
`docker logs docker_emulator_1 | egrep "pulse:|video:"`
