### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by dmarjanovic** [google/android-emulator-container-scripts#95]
After [this commit](https://github.com/google/android-emulator-container-scripts/commit/ea699521dd35e48801daa44971497bbc7737ee4b#diff-c78def91d8ea6c350b0f7b2e6f99708dR25) I started getting an error when using `emu-docker`:
```
(venv) [user@localhost android-emulator-container-scripts]$ emu-docker interactive
Traceback (most recent call last):
  File "/home/user/Code/google/android-emulator-container-scripts/venv/bin/emu-docker", line 11, in <module>
    load_entry_point('emu-docker', 'console_scripts', 'emu-docker')()
  File "/home/user/Code/google/android-emulator-container-scripts/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/Code/google/android-emulator-container-scripts/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/user/Code/google/android-emulator-container-scripts/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/user/Code/google/android-emulator-container-scripts/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/Code/google/android-emulator-container-scripts/emu/emu_docker.py", line 29, in <module>
    from emu.docker_device import DockerDevice
  File "/home/user/Code/google/android-emulator-container-scripts/emu/docker_device.py", line 25, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```
It worked fine after these two commands:
```
pip3 install --upgrade pip
pip3 install packaging
```

Not sure if it's python only thingy or related to this project but feel free to close if doesn't require any action on your side.

**Comment by pokowaka** [comment]
Yes, this needs to be fixed. I will add the dependency and make it explicit. Looks like this was in my global python install.
